from __future__ import annotations

from typing import Protocol
from websignal.models import NormalizedObservation


class Repository(Protocol):
    def ingest(self, observation: NormalizedObservation) -> tuple[bool, int]: ...
    def list_companies(self, technology: str | None, offset: int, limit: int) -> list[dict]: ...
    def get_company(self, domain: str) -> dict | None: ...
    def history(self, domain: str) -> list[dict]: ...
    def stats(self) -> dict: ...
